# Generated by Django 4.2 on 2023-04-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booking_organiser"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="details",
            field=models.TextField(default="details ..."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="title",
            field=models.CharField(default="Meeting", max_length=100),
            preserve_default=False,
        ),
    ]
