name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
            
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Generate Coverage Report
              run: |
                coverage run --source='.' --omit='suitedreams/wsgi.py','suitedreams/asgi.py','manage.py' manage.py test
                coverage report
                coverage html 

            - name: Upload coverage report to repo
              uses: actions/upload-artifact@v2
              with:
                name: coverage-report
                path: htmlcov/index.html

            - name: Generate coverage badge
              run: coverage-badge -f -o coverage.svg 

            - name: Upload coverage badge
              uses: actions/upload-artifact@v2 
              with: 
                name: coverage-badge
                path: coverage.svg

            
