name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
            
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Generate Coverage Report
              run: |
                coverage run --source='.' --omit='suitedreams/wsgi.py','suitedreams/asgi.py','manage.py' manage.py test
                coverage report
                coverage html 

            - name: Upload coverage report to repository
              uses: actions/upload-artifact@v2
              with:
                name: coverage-report
                path: htmlcov/index.html

            - name: Generate coverage badge
              run: |
               coverage-badge -o coverage.svg 

            - name: Upload coverage badge
              uses: actions/upload-artifact@v2 
              with: 
                name: coverage-badge
                path: coverage.svg

            - name: Add coverage badge to repository
              run: |
                    git config --global user.name "Adam Byrne"
                    git config --global user.email "adam.r.byrne@gmail.com"
                    git config advice.addIgnoredFile false
                    git add -f coverage.svg htmlcov/index.html
                    git commit -m "Added coverage data"
                    git push origin main

            

            
