name: Test

on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif

  coverage:
    runs-on: ubuntu-latest
    steps:
		# Generate coverage report
		- name: Generate Coverage Report
			run: |
			coverage run --source='.' --omit='suitedreams/wsgi.py','suitedreams/asgi.py','manage.py' manage.py test
			coverage report
			coverage html 

		- name: Upload coverage report to repo
			uses: actions/upload-artifact@v2
			with:
			name: coverage-report
			path: htmlcov/index.html

		- name: Generate coverage badge
			run: coverage-badge -f -o coverage.svg 

		- name: Upload coverage badge
			uses: actions/upload-artifact@v2 
			with: 
			name: coverage-badge
			path: coverage.svg